#! /bin/sh
#
# Line 2
#

. panel_colors-bar

while read -r line ; do
	case $line in
		T*)
			# xtitle output
			title="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG}${line#?}"
			;;
        player)
            # current song output
            #mtrack="$(mpc current)"
			mtrack="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG}$(echo $(mpc current) | cut -c1-100)"
            ;;
		C*)
			# primary selection
			selection="${line:1:100}"
			selection="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG}${selection//\%/\%\%}"
			;;
	esac
	#printf "%s\n" "%{l} $wm_infos %{c} $title %{r} $sys_infos  "
	printf "%s\n" "%{S1}%{l} $title %{r}${mtrack-$selection} "
done
