#! /bin/sh
#
# Example panel for LemonBoy's bar

. panel_colors-bar

while read -r line ; do
	case $line in
		S*)
			# clock output
			sys_infos="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG}${line#?} $(date +%D)"
			;;
		D*)
			# timeleft
			timeleft="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG}${line#?}"
			;;
        W*)
            # bspwm internal state
            wm_infos=""
            IFS=':'
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                name=${item#?}
                #dot_o=$' \u25A1 '
                dot_o=$' \u2662 '
                #dot_c=$' \u25A0 '
                dot_c=$' \u2666 '
                wm_infos="$wm_infos%{A:bspc desktop -f $name:}"

                case $item in
                    O*)
                        # focused occupied desktop
                        wm_infos="$wm_infos%{F$COLOR_FOCUSED_OCCUPIED_FG}%{B$COLOR_FOCUSED_OCCUPIED_BG}%{U$COLOR_FOREGROUND}%{+u}${name}%{-u}%{B$COLOR_FREE_BG}"
                        ;;
                    F*)
                        # focused free desktop
                        wm_infos="$wm_infos%{F$COLOR_FOCUSED_FREE_FG}%{B$COLOR_FOCUSED_FREE_BG}%{U$COLOR_FOREGROUND}%{+u}${name}%{-u}%{B$COLOR_FREE_BG}"
                        ;;
                    U*)
                        # focused urgent desktop
                        wm_infos="$wm_infos%{F$COLOR_FOCUSED_URGENT_FG}%{B$COLOR_FOCUSED_URGENT_BG}%{U$COLOR_FOREGROUND}%{+u}${name}%{-u}%{B$COLOR_FREE_BG}"
                        ;;
                    o*)
                        # occupied desktop
                        wm_infos="$wm_infos%{F$COLOR_OCCUPIED_FG}%{B$COLOR_OCCUPIED_BG}${name}%{B$COLOR_FREE_BG}"
                        ;;
                    f*)
                        # free desktop
                        wm_infos="$wm_infos%{F$COLOR_FREE_FG}%{B$COLOR_FREE_BG}${name}"
                        ;;
                    u*)
                        # urgent desktop
                        wm_infos="$wm_infos%{F$COLOR_URGENT_FG}%{B$COLOR_URGENT_BG}${name}"
                        ;;
                    L*)
                        # layout
                        layout=$(printf "%s" "${name}" | sed 's/\(.\).*/\U\1/')
                        wm_infos="$wm_infos %{F$COLOR_LAYOUT_FG}%{B$COLOR_LAYOUT_BG}$layout "
                        ;;
                esac
                wm_infos="$wm_infos%{A} "
                shift
            done
            ;;
		*)
			echo $line > $PANEL_FIFO2
			;;
	esac
	#printf "%s\n" "%{l} $wm_infos %{c} $title %{r} $sys_infos  "
	printf "%s\n" "%{S1}%{l}$wm_infos %{r} $timeleft | $sys_infos "
done
