#! /bin/sh

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

#PANEL_HEIGHT is 16
bspc config top_padding $PANEL_HEIGHT

bspc control --subscribe > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &
clock -sf 'S%a %H:%M' > "$PANEL_FIFO" &
mpc idleloop player > "$PANEL_FIFO" &
battery -n1 -sf "B%s%i" -i 60 > "$PANEL_FIFO" &
essid -w wifi0 -sf "E%s" -i 10 > "$PANEL_FIFO" &

function volume () {
	VOL=$(amixer sget Master | grep 'Front Left' | egrep -o '\[[0-9]{0,3}%\] \[(on|off)\]' | tr -d \[\])
	VOLSTATUS="$(echo $VOL | cut -d' ' -f2)"
	if [ "$VOLSTATUS" == "on" ]; then
		echo "$(echo "V$VOL" | cut -d' ' -f1)%"
	else
		echo "VM"
	fi
}

while true; do
	volume > "$PANEL_FIFO"
	sleep 5s || break
done &

#Countdown timer
#while true ; do
#		echo "D$(date -ud @"$(($(date -d '07:30' +%s) - $(date +%s)))" +'%-Hh %-Mm')" > "$PANEL_FIFO"
#		sleep 1m || break
#done &

function get_ip () {
	echo "$(ip addr show $1 | egrep -o 'inet [0-9\.]{7,15}' | sed "s/inet /$1:/") "
}

#ip address
while true ; do
	echo "I$(get_ip wifi0)$(get_ip net0)" > "$PANEL_FIFO"
	sleep 30s || break
done &

. panel_colors-bar

#FONT_FAMILY='-*-terminus-medium-r-normal-*-12-*-*-*-c-*-*-1'
FONT_FAMILY='-gohu-gohufont-medium-r-normal--11-80-100-100-c-60-iso10646-1'
cat "$PANEL_FIFO" | panel_bar | bar-aint-recursive -g x$PANEL_HEIGHT -f "$FONT_FAMILY" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" | bash &

wait
