# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

eval $(dircolors ~/.dircolors)

HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000

setopt appendhistory
setopt HIST_IGNORE_DUPS
setopt completealiases

#Source functions
[[ -f ~/.zsh_aliases ]] && source ~/.zsh_aliases
[[ -f ~/.zsh_functions ]] && source ~/.zsh_functions

#Common Aliases
alias ls='ls --color=auto'
alias grep='grep --colour=auto'
alias egrep='egrep --colour=auto'
alias fgrep='fgrep --colour=auto'
alias tree='tree -Csuh'
alias ..='cd ..'                                #Go up one directory
alias path='echo -e ${PATH//:/\\n}'

#Safety Aliases
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

#alias ssh='eval $(/usr/bin/keychain --eval --agents ssh -Q --quiet ~/.ssh/id_rsa) && TERM=xterm-color ssh'
