#! /bin/sh

bspc config border_width        2
bspc config window_gap         12

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d TERM1 TERM2 NS1 NS2 RTR1 RTR2 PCAP ARBOR MISC1 MISC2
#bspc monitor Virtual1 -n 0 -d 1 2 3 4 5 6 7 8 
#bspc monitor Virtual2 -n 1 -d 9 0
#bspc monitor -f 0

#bspc rule -a Gimp desktop=^8 follow=on floating=on
#bspc rule -a Chromium desktop=^2
#bspc rule -a mplayer2 floating=on
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a Gifview floating=on
bspc rule -a vlc floating=on sticky=on
bspc rule -a MPlayer floating=on
bspc rule -a dosbox floating=on

#urxvtd --quiet --opendisplay --fork
compton -b
twmnd &

[[ -f ~/.config/bspwm/saved ]] && rm -f ~/.config/bspwm/saved;

PATH=$PATH:$HOME/panel

sleep 2s && panel &>> ~/.config/bspwm/panel.log &
sleep 10s && eval $(cat ~/.fehbg) &
